
# 뭔진 모르겠지만 일단 쿼리가 보인다.
logging:
  level:
    org:
      springframework:
        data: INFO
        jdbc.core.JdbcTemplate: DEBUG


      jooq:
        tools:
          LoggerListener: DEBUG
spring:
  datasource:
    url: jdbc:h2:tcp:localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver
  jooq:
    sql-dialect: h2


